# Explicit runtime sources. Do not glob core/*.c or kernel/*.c.
set(L2D_RUNTIME_SOURCES
    src/engine/live2d_engine.c
    src/api/l2d_api.c
    src/memory/l2d_allocator.c
    src/memory/l2d_arena.c
    src/format/l2d_wire.c
    src/pipeline/l2d_roi.c
    src/raster/l2d_raster_nearest.c
    src/internal/pe/core/PX_Typedef.c
    src/internal/pe/core/PX_Log.c
    src/internal/pe/core/PX_MemoryPool.c
    src/internal/pe/core/PX_Vector.c
    src/internal/pe/core/PX_Quicksort.c
    src/internal/pe/core/PX_Surface.c
    src/internal/pe/core/PX_Texture.c
    src/internal/pe/kernel/PX_LiveFramework.c
    src/internal/pe/kernel/PX_LiveRealtime.c
    src/internal/pe/kernel/PX_LiveDeviceFormat.c
)
